# https://taskfile.dev

version: "3"

vars:

tasks:
  default:
    cmds:
      - task $(cat ./Taskfile.yml | yq '.tasks|keys|.[]' | fzf)
    silent: true
  deploy:*:
    vars:
      BUILD: "{{index .MATCH 0}}"
    cmds:
      - nix build .#{{.BUILD}}
      - cp result/index.html index.html
      - git add index.html
        && git commit -m "{{.BUILD}}"
        && git push
        && git status
        && echo "git push success"
        || echo "git push failed"
  git-add-commit-push:
    cmds:
      - git add .
        && git commit -m "update"
        && git push
        && git status
        && echo "git push success"
        || echo "git push failed"
  mdimg:
    cmds:
      - echo -n '![{{.CLI_ARGS}}]('$(task awkimg -- {{.CLI_ARGS}})')'
    silent: true
  awkimg:
    vars:
      TGPT:
        sh: which tgpt
    cmds:
      - curl --no-progress-meter -F"file=@$('{{.TGPT}}' --img --height 630 --width 1200 "{{.CLI_ARGS}}" | awk '{match($0, /Saved image as ([^ ]+\.jpg)/, arr);  if (arr[1] != "") {print arr[1]} }')" https://envs.sh
    silent: true
  exit:
    cmds:
      - exit
